config/routes.rb
SOC::Application.routes.draw do



  root to: 'pages#root'


  resources :users, only: [:new, :create]
  
  resource :session, only: [:new, :create, :destroy, :show]
  
  
  namespace :api, defaults: { format: :json } do
    resources :users, except: [:new, :create]
    resources :questions, except: [:new, :edit]
    resources :answers, only: [:create, :update, :destroy]
    resources :comments, only: [:create, :update, :destroy]
    resources :votes, only: [:create, :destroy, :show, :update]
    resources :tags, except: [:new, :edit]
    resources :favorite_tags, only: [:create, :destroy]
    resources :question_tags, only: [:create, :destroy]
  end
  
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
<div class="container container-fluid">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/#">StackOverflow Clone</a>
      <% if current_user %>
      <a class="navbar-brand" style="margin-left: 20px; font-size: 18px;" href="/#users/<%=current_user.id%>">Signed in: <%=current_user.username%></a></li>
      <% end %>

  </div>

  <div class="collapse navbar-collapse pull-right" id="bs-example-navbar-collapse-1">

    <ul class="nav navbar-nav">
      <li style="font-size: 18px;"><a id="nav-askquestion" href="/#questions/new">Ask Question</a></li>

      <% if current_user %>

    <li><%= button_to "Sign out", session_url, method: :delete, class: "btn btn-primary navbar-btn", style: "font-size: 18px;"%></li>
    
    <% else %>
      <li  style="font-size: 18px;"><%= link_to "Log in", new_session_url %></li>
      <li  style="font-size: 18px;"><%= link_to "Sign up", new_user_url %></li>
    </ul>
    <% end %>
  </div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StackOverflowClone</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render partial: "layouts/header" %>

            

<br>
<br>
<br>
<br>

<%= yield %>

</body>
</html>